# -*- coding: utf-8 -*-
"""convert_to_matcher_format

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OlhUqXjt70uVScF2_cPo2vEgQFqP3Ie
"""

# -*- coding: utf-8 -*-
"""
因为在我这里，我更多的是使用dtype20, w_name_o, w_name这几个变量名称，所以需要这样一个转换文件变更一下变量名来兼容gui.py。这个代码文件是一个模版，其他情况请按照具体情况调整内容。
数据格式转换脚本：将现有的 (dtype20, w_name_o, w_name) 数据
转换为 matcher 系统所需的 codebook.xlsx 和 training_data.xlsx
"""

import pandas as pd
import hashlib
import os
from datetime import datetime

# ============================================================
# 1. 配置区域（请根据你的实际情况修改）
# ============================================================
INPUT_FILE = "原始数据.xlsx"  # 改成文件名

# 列名映射（如果你的列名不同，请在这里修改）
COL_MAP = {
    "dtype20": "dtype20",       # 层级列（如：省/地级市/区/县...）
    "w_name_o": "w_name_o",     # 原始别名列（如：省发改委）
    "w_name": "w_name"          # 标准全称列（如：广东省发展和改革委员会）
}

# ============================================================
# 2. 读取数据
# ============================================================
df_raw = pd.read_excel(INPUT_FILE, dtype=str).fillna("")
print(f"✅ 读取到 {len(df_raw)} 条原始记录")

# 重命名列以便统一处理
df = df_raw.rename(columns={
    COL_MAP["dtype20"]: "dtype20",
    COL_MAP["w_name_o"]: "w_name_o",
    COL_MAP["w_name"]: "w_name"
})

# ============================================================
# 3. 层级标准化函数
# ============================================================
def map_level(dtype_val):
    """将你数据里的各种层级描述映射为系统标准的三档"""
    val = str(dtype_val).strip()
    if val in ["省", "省级"]:
        return "省级"
    elif val in ["地级市", "市", "市级"]:
        return "市级"
    elif val in ["县", "县级", "区", "县级市", "经济区", "功能区"]:
        return "县级"
    else:
        # 如果出现未知层级，会在这里停住提醒你
        raise ValueError(f"未知层级: '{val}'，请在 map_level 中补充映射规则")

def generate_hash_id(standard_name, level):
    """根据标准名+层级生成确定性的 8 位哈希 ID"""
    raw = f"{standard_name}_{level}"
    return hashlib.md5(raw.encode('utf-8')).hexdigest()[:8]

# ============================================================
# 4. 构建 codebook.xlsx（标准部门编码池）
# ============================================================
print("\n正在构建 codebook...")

# 应用层级映射
df['level'] = df['dtype20'].apply(map_level)

# 按 (w_name, level) 分组，聚合所有别名
grouped = df.groupby(['w_name', 'level'], as_index=False).agg({
    'w_name_o': lambda x: '|'.join(sorted(set(x)))  # 去重后用 | 拼接
})
grouped = grouped.rename(columns={'w_name': 'standard_name', 'w_name_o': 'aliases'})

# 生成 dept_id
grouped['dept_id'] = grouped.apply(
    lambda r: generate_hash_id(r['standard_name'], r['level']), axis=1
)

# 整理成 codebook 标准格式
codebook = grouped[['dept_id', 'level', 'standard_name', 'aliases']]
codebook.to_excel("codebook.xlsx", index=False)
print(f"✅ codebook.xlsx 已生成！共 {len(codebook)} 个部门概念")

# ============================================================
# 5. 构建 training_data.xlsx（标准训练数据集）
# ============================================================
print("\n正在构建 training_data...")

# 将原始数据与 codebook 的 dept_id 做关联
train_merge = df.merge(
    codebook[['dept_id', 'standard_name', 'level']],
    left_on=['w_name', 'level'],
    right_on=['standard_name', 'level'],
    how='left'
)

# 检查是否有无法匹配的数据
missing = train_merge[train_merge['dept_id'].isna()]
if len(missing) > 0:
    print(f"⚠️ 警告：有 {len(missing)} 条记录的 w_name 在 codebook 中找不到对应，请检查")
    print("   （这些行将被过滤掉）")
    train_merge = train_merge.dropna(subset=['dept_id'])

# 取出系统训练所需的 3 列
training_data = train_merge[['w_name_o', 'dtype20', 'dept_id']].rename(
    columns={'dtype20': 'dtype_t'}
)
training_data.to_excel("training_data.xlsx", index=False)
print(f"✅ training_data.xlsx 已生成！共 {len(training_data)} 条有效训练记录")

# ============================================================
# 6. 完成提示 + 数据统计
# ============================================================
print("\n" + "="*70)
print("🎉 转换完成！以下是生成的文件：")
print("  📄 codebook.xlsx      -> 标准部门编码池（共 {} 个部门概念）".format(len(codebook)))
print("  📄 training_data.xlsx -> 标准训练数据集（共 {} 条记录）".format(len(training_data)))

# 打印一些统计信息
print("\n📊 层级分布统计（codebook）：")
print(codebook['level'].value_counts().to_string())

# 展示几条样例
print("\n📋 codebook 前 5 行预览：")
print(codebook.head().to_string())

print("\n📋 training_data 前 5 行预览：")
print(training_data.head().to_string())

print("\n" + "="*70)
print("🚀 下一步：")
print("  1. 将生成的 codebook.xlsx 和 training_data.xlsx 放到 matcher.py 同级目录")
print("  2. 运行 python gui.py 启动图形界面")
print("  3. 在「模型训练与评估」页签点击「开始训练」，生成 model.pkl")
print("  4. 开始使用！")
print("="*70)