# -*- coding: utf-8 -*-
"""gui.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148q5vgIMjnRhZaw_5soXpiC9q4eHTmKF
"""

# -*- coding: utf-8 -*-
"""
gui.py — 部门名称标准化匹配系统界面 (v2)
四个页签：单条查询 / 批量处理 / 部门库管理 / 模型训练与评估
批量处理与模型训练均在后台线程运行，避免界面卡死。
"""
import os
import queue
import threading
from datetime import datetime

import tkinter as tk
from tkinter import ttk, filedialog, messagebox, scrolledtext

import pandas as pd

from matcher import DeptMatcher, MatcherError, CodeBookError, LEVEL_MAP, CFG

CODEBOOK_PATH = "codebook.xlsx"
MODEL_PATH = "model.pkl"
TRAIN_PATH = "training_data.xlsx"
DTYPE_OPTIONS = ["省", "地级市", "县", "区", "县级市", "经济区", "旅游局", "功能区"]
LEVEL_FILTER_OPTIONS = ["全部", "省级", "市级", "县级"]

CONF_TAGS = {"高": "conf_high", "中": "conf_mid", "低": "conf_low"}


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("广东省行政部门名称标准化匹配系统")
        self.geometry("1000x680")
        self._setup_style()

        try:
            self.matcher = DeptMatcher(CODEBOOK_PATH, MODEL_PATH)
        except (CodeBookError, MatcherError) as e:
            messagebox.showerror("初始化失败", str(e))
            self.destroy()
            return

        nb = ttk.Notebook(self)
        nb.pack(fill="both", expand=True, padx=6, pady=6)
        self.tab_query = ttk.Frame(nb); nb.add(self.tab_query, text="单条查询")
        self.tab_batch = ttk.Frame(nb); nb.add(self.tab_batch, text="批量处理")
        self.tab_codebook = ttk.Frame(nb); nb.add(self.tab_codebook, text="部门库管理")
        self.tab_train = ttk.Frame(nb); nb.add(self.tab_train, text="模型训练与评估")

        self._build_query_tab()
        self._build_batch_tab()
        self._build_codebook_tab()
        self._build_train_tab()

        self.status_var = tk.StringVar()
        ttk.Label(self, textvariable=self.status_var, relief="sunken", anchor="w"
                  ).pack(fill="x", side="bottom")
        self._refresh_status()

    def _setup_style(self):
        style = ttk.Style(self)
        try:
            style.theme_use("clam")
        except tk.TclError:
            pass

    def _refresh_status(self):
        stats = self.matcher.codebook.stats
        txt = (f"Codebook: {stats['部门概念数']}个部门概念 / {stats['变体总数(含别名)']}个变体  |  "
               f"模型状态: {self.matcher.model_status}")
        self.status_var.set(txt)

    # ================= 单条查询 =================
    def _build_query_tab(self):
        f = self.tab_query
        top = ttk.Frame(f); top.pack(fill="x", padx=10, pady=10)

        ttk.Label(top, text="原始部门名 w_name_o：").grid(row=0, column=0, sticky="e", padx=4, pady=4)
        self.entry_raw = ttk.Entry(top, width=40)
        self.entry_raw.grid(row=0, column=1, padx=4, pady=4)
        self.entry_raw.bind("<Return>", lambda e: self.on_query())

        ttk.Label(top, text="层级 dtype_t：").grid(row=1, column=0, sticky="e", padx=4, pady=4)
        self.combo_level = ttk.Combobox(top, values=DTYPE_OPTIONS, width=37, state="readonly")
        self.combo_level.grid(row=1, column=1, padx=4, pady=4)
        self.combo_level.current(0)

        ttk.Button(top, text="查询 (Enter)", command=self.on_query).grid(row=0, column=2, rowspan=2, padx=10)

        cols = ("rank", "standard_name", "score", "confidence", "dept_id")
        headers = ("排名", "候选标准名", "相似度得分", "置信度", "dept_id")
        self.tree = ttk.Treeview(f, columns=cols, show="headings", height=6)
        for c, h, w in zip(cols, headers, (50, 320, 100, 80, 140)):
            self.tree.heading(c, text=h)
            self.tree.column(c, width=w, anchor="center")
        self.tree.tag_configure("conf_high", background="#d9f2d9")
        self.tree.tag_configure("conf_mid", background="#fff3cd")
        self.tree.tag_configure("conf_low", background="#fadbd8")
        self.tree.pack(fill="x", padx=10, pady=6)

        btn_frame = ttk.Frame(f); btn_frame.pack(fill="x", padx=10, pady=4)
        ttk.Button(btn_frame, text="✔ 确认所选结果为正确答案", command=self.on_confirm).pack(side="left", padx=4)
        ttk.Button(btn_frame, text="✘ 均不匹配，标记待人工新增", command=self.on_flag_unmatched).pack(side="left", padx=4)

        ttk.Label(f, text="本次会话操作记录：").pack(anchor="w", padx=10, pady=(10, 0))
        self.session_log = scrolledtext.ScrolledText(f, height=10, state="disabled")
        self.session_log.pack(fill="both", expand=True, padx=10, pady=6)

    def _log_session(self, text: str):
        self.session_log.configure(state="normal")
        self.session_log.insert("end", f"[{datetime.now().strftime('%H:%M:%S')}] {text}\n")
        self.session_log.see("end")
        self.session_log.configure(state="disabled")

    def on_query(self):
        raw, dtype_t = self.entry_raw.get().strip(), self.combo_level.get()
        if not raw:
            messagebox.showwarning("提示", "请输入原始部门名称")
            return
        try:
            res = self.matcher.query(raw, dtype_t, topk=3)
        except MatcherError as e:
            messagebox.showerror("查询失败", str(e))
            return
        for i in self.tree.get_children():
            self.tree.delete(i)
        for _, r in res.iterrows():
            tag = CONF_TAGS.get(r["confidence"], "")
            self.tree.insert("", "end",
                              values=(r["rank"], r["standard_name"], r["score"], r["confidence"], r["dept_id"]),
                              tags=(tag,))
        self._log_session(f"查询 '{raw}'({dtype_t}) -> 返回{len(res)}个候选")

    def on_confirm(self):
        sel = self.tree.selection()
        if not sel:
            messagebox.showwarning("提示", "请先在结果列表中选中正确的一项")
            return
        vals = self.tree.item(sel[0], "values")
        dept_id, standard_name = vals[4], vals[1]
        raw, dtype_t = self.entry_raw.get().strip(), self.combo_level.get()
        try:
            self.matcher.confirm(raw, dtype_t, dept_id)
        except MatcherError as e:
            messagebox.showerror("确认失败", str(e))
            return
        self._log_session(f"确认 '{raw}' -> {standard_name}({dept_id})，已写入别名库")
        self._refresh_status()
        self.entry_raw.delete(0, "end")
        for i in self.tree.get_children():
            self.tree.delete(i)

    def on_flag_unmatched(self):
        raw, dtype_t = self.entry_raw.get().strip(), self.combo_level.get()
        if not raw:
            messagebox.showwarning("提示", "请输入原始部门名称")
            return
        self.matcher.flag_unmatched(raw, dtype_t)
        self._log_session(f"标记 '{raw}'({dtype_t}) 为无匹配，已记入 unmatched_log.xlsx 待人工新增")

    # ================= 批量处理 =================
    def _build_batch_tab(self):
        f = self.tab_batch
        top = ttk.Frame(f); top.pack(fill="x", padx=10, pady=10)

        self.batch_path = tk.StringVar()
        ttk.Button(top, text="选择待处理 xlsx（需含 w_name_o, dtype_t 列）",
                   command=self.choose_batch_file).grid(row=0, column=0, padx=4, pady=4)
        ttk.Label(top, textvariable=self.batch_path).grid(row=0, column=1, sticky="w", padx=4)

        ttk.Label(top, text="返回候选数 Top-K：").grid(row=1, column=0, sticky="e", padx=4, pady=4)
        self.topk_var = tk.IntVar(value=3)
        ttk.Spinbox(top, from_=1, to=5, textvariable=self.topk_var, width=5).grid(row=1, column=1, sticky="w")

        self.batch_preview = ttk.Label(f, text="", foreground="#555")
        self.batch_preview.pack(anchor="w", padx=10)

        self.run_batch_btn = ttk.Button(f, text="开始批量匹配并导出结果", command=self.run_batch)
        self.run_batch_btn.pack(pady=10)

        self.batch_progress = ttk.Progressbar(f, orient="horizontal", length=500, mode="determinate")
        self.batch_progress.pack(pady=4)
        self.batch_status = ttk.Label(f, text="")
        self.batch_status.pack(pady=4)

        self._batch_queue: "queue.Queue" = queue.Queue()

    def choose_batch_file(self):
        path = filedialog.askopenfilename(filetypes=[("Excel files", "*.xlsx")])
        if not path:
            return
        try:
            df = pd.read_excel(path, dtype=str)
        except Exception as e:
            messagebox.showerror("读取失败", str(e))
            return
        if not {"w_name_o", "dtype_t"}.issubset(df.columns):
            messagebox.showerror("格式错误", "文件必须包含 w_name_o 和 dtype_t 两列")
            return
        self.batch_path.set(path)
        self.batch_preview.config(text=f"共 {len(df)} 行数据，列: {list(df.columns)}")
        self._batch_df = df

    def run_batch(self):
        if not getattr(self, "_batch_df", None) is not None:
            pass
        if not hasattr(self, "_batch_df"):
            messagebox.showwarning("提示", "请先选择文件")
            return
        self.run_batch_btn.config(state="disabled")
        self.batch_progress["value"] = 0
        self.batch_status.config(text="处理中...")

        def worker():
            try:
                def cb(done, total):
                    self._batch_queue.put(("progress", done, total))
                result = self.matcher.batch_query(self._batch_df, topk=self.topk_var.get(),
                                                   progress_callback=cb)
                self._batch_queue.put(("done", result))
            except Exception as e:
                self._batch_queue.put(("error", str(e)))

        threading.Thread(target=worker, daemon=True).start()
        self.after(150, self._poll_batch_queue)

    def _poll_batch_queue(self):
        try:
            while True:
                msg = self._batch_queue.get_nowait()
                if msg[0] == "progress":
                    _, done, total = msg
                    self.batch_progress["maximum"] = total
                    self.batch_progress["value"] = done
                    self.batch_status.config(text=f"已处理 {done}/{total}")
                elif msg[0] == "done":
                    result = msg[1]
                    self._on_batch_done(result)
                    return
                elif msg[0] == "error":
                    messagebox.showerror("批量处理失败", msg[1])
                    self.run_batch_btn.config(state="normal")
                    return
        except queue.Empty:
            pass
        self.after(150, self._poll_batch_queue)

    def _on_batch_done(self, result: pd.DataFrame):
        self.run_batch_btn.config(state="normal")
        n_low = (result.get("置信度1", pd.Series(dtype=str)) == "低").sum()
        n_none = (result.get("_备注", pd.Series(dtype=str)) != "").sum()
        self.batch_status.config(
            text=f"完成！共 {len(result)} 条，低置信度 {n_low} 条，需人工核查 {n_none} 条")
        out_path = filedialog.asksaveasfilename(defaultextension=".xlsx",
                                                  filetypes=[("Excel files", "*.xlsx")])
        if out_path:
            result.to_excel(out_path, index=False)
            messagebox.showinfo("已保存", f"结果已保存至：\n{out_path}")
        self._refresh_status()

    # ================= 部门库管理 =================
    def _build_codebook_tab(self):
        f = self.tab_codebook
        top = ttk.Frame(f); top.pack(fill="x", padx=10, pady=10)

        ttk.Label(top, text="层级：").grid(row=0, column=0, padx=4)
        self.cb_level_filter = ttk.Combobox(top, values=LEVEL_FILTER_OPTIONS, width=10, state="readonly")
        self.cb_level_filter.grid(row=0, column=1, padx=4)
        self.cb_level_filter.current(0)

        ttk.Label(top, text="关键词：").grid(row=0, column=2, padx=4)
        self.cb_keyword = ttk.Entry(top, width=25)
        self.cb_keyword.grid(row=0, column=3, padx=4)
        self.cb_keyword.bind("<Return>", lambda e: self.on_search_codebook())

        ttk.Button(top, text="搜索", command=self.on_search_codebook).grid(row=0, column=4, padx=8)

        cols = ("dept_id", "level", "standard_name", "aliases")
        headers = ("dept_id", "层级", "标准名", "别名(用|分隔)")
        self.cb_tree = ttk.Treeview(f, columns=cols, show="headings", height=14)
        for c, h, w in zip(cols, headers, (140, 70, 220, 380)):
            self.cb_tree.heading(c, text=h)
            self.cb_tree.column(c, width=w, anchor="w")
        self.cb_tree.pack(fill="both", expand=True, padx=10, pady=6)
        self.on_search_codebook()

        # 新增部门表单
        add_frame = ttk.LabelFrame(f, text="新增部门（当确实是codebook中没有的新部门时使用）")
        add_frame.pack(fill="x", padx=10, pady=10)
        ttk.Label(add_frame, text="dept_id：").grid(row=0, column=0, padx=4, pady=4)
        self.new_dept_id = ttk.Entry(add_frame, width=18)
        self.new_dept_id.grid(row=0, column=1, padx=4)
        ttk.Label(add_frame, text="层级：").grid(row=0, column=2, padx=4)
        self.new_level = ttk.Combobox(add_frame, values=["省级", "市级", "县级"], width=8, state="readonly")
        self.new_level.grid(row=0, column=3, padx=4); self.new_level.current(0)
        ttk.Label(add_frame, text="标准名：").grid(row=0, column=4, padx=4)
        self.new_std_name = ttk.Entry(add_frame, width=20)
        self.new_std_name.grid(row=0, column=5, padx=4)
        ttk.Label(add_frame, text="别名(可选,|分隔)：").grid(row=0, column=6, padx=4)
        self.new_aliases = ttk.Entry(add_frame, width=20)
        self.new_aliases.grid(row=0, column=7, padx=4)
        ttk.Button(add_frame, text="添加", command=self.on_add_department).grid(row=0, column=8, padx=8)

    def on_search_codebook(self):
        level = self.cb_level_filter.get()
        kw = self.cb_keyword.get().strip()
        df = self.matcher.codebook.search(level=level, keyword=kw)
        for i in self.cb_tree.get_children():
            self.cb_tree.delete(i)
        for _, r in df.iterrows():
            self.cb_tree.insert("", "end", values=(r["dept_id"], r["level"], r["standard_name"], r["aliases"]))

    def on_add_department(self):
        dept_id = self.new_dept_id.get().strip()
        level = self.new_level.get()
        std_name = self.new_std_name.get().strip()
        aliases = self.new_aliases.get().strip()
        if not dept_id or not std_name:
            messagebox.showwarning("提示", "dept_id 和标准名不能为空")
            return
        try:
            self.matcher.codebook.add_department(dept_id, level, std_name, aliases)
            self.matcher.codebook.save()
            self.matcher._cache.clear()
        except CodeBookError as e:
            messagebox.showerror("添加失败", str(e))
            return
        messagebox.showinfo("成功", f"已添加部门：{std_name}（{dept_id}, {level}）")
        self.on_search_codebook()
        self._refresh_status()

    # ================= 模型训练与评估 =================
    def _build_train_tab(self):
        f = self.tab_train
        top = ttk.Frame(f); top.pack(fill="x", padx=10, pady=10)

        self.train_path_var = tk.StringVar(value=TRAIN_PATH)
        ttk.Button(top, text="选择训练数据 xlsx", command=self.choose_train_file).grid(row=0, column=0, padx=4)
        ttk.Label(top, textvariable=self.train_path_var).grid(row=0, column=1, sticky="w", padx=4)

        ttk.Label(top, text="需含列：w_name_o, dtype_t, dept_id", foreground="#777").grid(
            row=1, column=0, columnspan=2, sticky="w", padx=4)

        opt_frame = ttk.Frame(f); opt_frame.pack(fill="x", padx=10, pady=6)
        self.model_type_var = tk.StringVar(value="logistic")
        ttk.Radiobutton(opt_frame, text="逻辑回归（推荐，稳定可解释）", value="logistic",
                         variable=self.model_type_var).grid(row=0, column=0, sticky="w", padx=4)
        ttk.Radiobutton(opt_frame, text="随机森林（数据量大时更强）", value="rf",
                         variable=self.model_type_var).grid(row=1, column=0, sticky="w", padx=4)

        ttk.Label(opt_frame, text="验证集比例：").grid(row=0, column=1, sticky="e", padx=(20, 4))
        self.test_size_var = tk.DoubleVar(value=0.2)
        ttk.Spinbox(opt_frame, from_=0.1, to=0.4, increment=0.05, textvariable=self.test_size_var,
                    width=6).grid(row=0, column=2, sticky="w")

        ttk.Label(opt_frame, text="难负例数量：").grid(row=1, column=1, sticky="e", padx=(20, 4))
        self.hard_neg_var = tk.IntVar(value=6)
        ttk.Spinbox(opt_frame, from_=2, to=15, textvariable=self.hard_neg_var, width=6).grid(
            row=1, column=2, sticky="w")

        self.train_btn = ttk.Button(f, text="开始训练 / 重新训练", command=self.run_train)
        self.train_btn.pack(pady=10)
        self.train_status = ttk.Label(f, text="", font=("", 11, "bold"))
        self.train_status.pack(pady=4)

        ttk.Label(f, text="训练历史记录：").pack(anchor="w", padx=10)
        self.train_log = scrolledtext.ScrolledText(f, height=14, state="disabled")
        self.train_log.pack(fill="both", expand=True, padx=10, pady=6)

        self._train_queue: "queue.Queue" = queue.Queue()

    def choose_train_file(self):
        path = filedialog.askopenfilename(filetypes=[("Excel files", "*.xlsx")])
        if path:
            self.train_path_var.set(path)

    def run_train(self):
        path = self.train_path_var.get()
        if not os.path.exists(path):
            messagebox.showerror("错误", f"找不到训练数据文件：{path}")
            return
        self.train_btn.config(state="disabled")
        self.train_status.config(text="训练中，请稍候...")

        def worker():
            try:
                metrics = self.matcher.train(
                    path, MODEL_PATH,
                    model_type=self.model_type_var.get(),
                    test_size=self.test_size_var.get(),
                    hard_negatives=self.hard_neg_var.get(),
                )
                self._train_queue.put(("done", metrics))
            except MatcherError as e:
                self._train_queue.put(("error", str(e)))
            except Exception as e:
                self._train_queue.put(("error", f"未知错误: {e}"))

        threading.Thread(target=worker, daemon=True).start()
        self.after(200, self._poll_train_queue)

    def _poll_train_queue(self):
        try:
            msg = self._train_queue.get_nowait()
        except queue.Empty:
            self.after(200, self._poll_train_queue)
            return

        self.train_btn.config(state="normal")
        if msg[0] == "error":
            self.train_status.config(text="训练失败")
            messagebox.showerror("训练失败", msg[1])
            return

        metrics = msg[1]
        top1 = metrics.get("top1_acc")
        top3 = metrics.get("top3_acc")
        if top1 is not None:
            summary = (f"训练完成！训练样本={metrics['n_train']}，验证样本={metrics['n_val']}，"
                       f"Top1准确率={top1:.1%}，Top3准确率={top3:.1%}")
        else:
            summary = f"训练完成！样本数={metrics['n_train']}（样本量过小，未做验证集评估）"
        self.train_status.config(text=summary)

        self.train_log.configure(state="normal")
        self.train_log.insert("end", f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] {summary}\n")
        self.train_log.see("end")
        self.train_log.configure(state="disabled")
        self._refresh_status()


if __name__ == "__main__":
    App().mainloop()