# -*- coding: utf-8 -*-
"""matcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhiiLGjBZcXZrR073fVO57Anm4-AT_m3
"""

# -*- coding: utf-8 -*-
"""
matcher.py — 广东省行政部门名称标准化匹配引擎 (v2)
============================================================
架构说明：
  - CodeBook   : 编码池管理（加载/校验/备份/别名增长/浏览）
  - DeptMatcher: 匹配引擎
      · query()       单条查询 —— 精确穷举比对，优先保证准确率
      · batch_query() 批量查询 —— 两阶段"检索+精排"，兼顾效率与准确率
      · train()       基于历史人工编码数据训练/更新重排序模型
      · confirm()      人工确认写回别名库，形成"记忆式"零成本学习
"""

import os
import re
import shutil
import logging
import unicodedata
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from rapidfuzz import fuzz
from rapidfuzz.distance import JaroWinkler

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity

import joblib

# ============================================================
# 日志配置
# ============================================================
LOG_PATH = "matcher.log"
logger = logging.getLogger("dept_matcher")
if not logger.handlers:
    logger.setLevel(logging.INFO)
    fh = logging.FileHandler(LOG_PATH, encoding="utf-8")
    fh.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))
    logger.addHandler(fh)


# ============================================================
# 常量与配置
# ============================================================
LEVEL_MAP = {
    "省": "省级",
    "地级市": "市级", "市": "市级",
    "县": "县级", "区": "县级", "县级市": "县级",
    "经济区": "县级", "功能区": "县级",
}

FEATURE_NAMES = ["ratio", "partial_ratio", "token_sort_ratio",
                 "jaro_winkler", "dice", "lcs_ratio", "tfidf_cos",
                 "len_ratio", "exact"]

# 冷启动（未训练模型时）的启发式加权融合系数
HEURISTIC_WEIGHTS = {
    "ratio": 0.22, "partial_ratio": 0.10, "token_sort_ratio": 0.10,
    "jaro_winkler": 0.10, "dice": 0.18, "lcs_ratio": 0.10,
    "tfidf_cos": 0.15, "len_ratio": 0.05, "exact": 0.0,
}


@dataclass
class MatcherConfig:
    stage1_topn: int = 30       # 批量模式候选检索阶段保留的候选部门数
    chunk_size: int = 2000      # 批量向量化时每批的行数上限（内存保护）
    high_conf_thresh: float = 0.85
    mid_conf_thresh: float = 0.60


CFG = MatcherConfig()


class CodeBookError(Exception):
    pass


class MatcherError(Exception):
    pass


@dataclass
class MatchResult:
    dept_id: str
    standard_name: str
    score: float
    confidence: str


# ============================================================
# 文本处理工具
# ============================================================
_PUNCT_RE = re.compile(r"[\s\u3000（）()【】\[\]:：·,，、\.。;；\"'“”‘’\-—]")


def normalize_text(s) -> str:
    """全角/半角统一 + 去除常见标点空白，避免无意义差异干扰相似度计算"""
    if pd.isna(s):
        return ""
    s = unicodedata.normalize("NFKC", str(s))
    return _PUNCT_RE.sub("", s).strip()


def map_level(dtype_t: str) -> str:
    key = str(dtype_t).strip()
    lvl = LEVEL_MAP.get(key)
    if lvl is None:
        raise MatcherError(
            f"未知的 dtype_t: '{dtype_t}'，应为 省/地级市/县/区/县级市/经济区/功能区 之一"
        )
    return lvl


def confidence_tier(score: float) -> str:
    if score >= CFG.high_conf_thresh:
        return "高"
    elif score >= CFG.mid_conf_thresh:
        return "中"
    return "低"


def _lcs_length(a: str, b: str) -> int:
    n, m = len(a), len(b)
    if n == 0 or m == 0:
        return 0
    prev = [0] * (m + 1)
    for i in range(1, n + 1):
        cur = [0] * (m + 1)
        ai = a[i - 1]
        for j in range(1, m + 1):
            cur[j] = prev[j - 1] + 1 if ai == b[j - 1] else max(prev[j], cur[j - 1])
        prev = cur
    return prev[m]


def lcs_ratio(a: str, b: str) -> float:
    """最长公共子序列比例：专门捕捉'发展和改革委员会→发改委'这类逐字提取式缩写"""
    if not a or not b:
        return 0.0
    return _lcs_length(a, b) / max(len(a), len(b))


def char_dice(a: str, b: str) -> float:
    def bigrams(s):
        return {s[i:i + 2] for i in range(len(s) - 1)} if len(s) > 1 else {s}
    A, B = bigrams(a), bigrams(b)
    if not A or not B:
        return 0.0
    return 2 * len(A & B) / (len(A) + len(B))


def extract_features(raw_n: str, cand_n: str, tfidf_cos: float) -> np.ndarray:
    exact = 1.0 if (raw_n == cand_n and raw_n != "") else 0.0
    feats = {
        "ratio": fuzz.ratio(raw_n, cand_n) / 100.0,
        "partial_ratio": fuzz.partial_ratio(raw_n, cand_n) / 100.0,
        "token_sort_ratio": fuzz.token_sort_ratio(raw_n, cand_n) / 100.0,
        "jaro_winkler": JaroWinkler.normalized_similarity(raw_n, cand_n),
        "dice": char_dice(raw_n, cand_n),
        "lcs_ratio": lcs_ratio(raw_n, cand_n),
        "tfidf_cos": float(tfidf_cos),
        "len_ratio": min(len(raw_n), len(cand_n)) / max(len(raw_n), len(cand_n), 1),
        "exact": exact,
    }
    return np.array([feats[k] for k in FEATURE_NAMES], dtype=float)


def heuristic_score(feat_vec: np.ndarray) -> float:
    d = dict(zip(FEATURE_NAMES, feat_vec))
    if d["exact"] == 1.0:
        return 1.0
    return float(sum(d[k] * HEURISTIC_WEIGHTS[k] for k in FEATURE_NAMES))


# ============================================================
# CodeBook 编码池
# ============================================================
class CodeBook:
    REQUIRED_COLS = ["dept_id", "level", "standard_name", "aliases"]

    def __init__(self, path: str, backup_dir: str = "codebook_backups"):
        if not os.path.exists(path):
            raise CodeBookError(f"找不到 codebook 文件: {path}")
        self.path = path
        self.backup_dir = backup_dir
        os.makedirs(backup_dir, exist_ok=True)
        self.df = pd.read_excel(path, dtype=str).fillna("")
        self._validate()
        self.vectorizer: Optional[TfidfVectorizer] = None
        self.tfidf_matrix = None
        self.expanded: pd.DataFrame = pd.DataFrame()
        self._build_index()

    def _validate(self):
        missing = set(self.REQUIRED_COLS) - set(self.df.columns)
        if missing:
            raise CodeBookError(f"codebook 缺少必要列: {missing}")
        empty_names = self.df[self.df["standard_name"].str.strip() == ""]
        if len(empty_names) > 0:
            logger.warning(f"codebook 中有 {len(empty_names)} 行 standard_name 为空")
        dup = self.df.duplicated(subset=["dept_id", "level"], keep=False)
        if dup.any():
            logger.warning(f"codebook 中存在 {dup.sum()} 行 (dept_id, level) 重复，建议核查")

    def _build_index(self):
        self.df["norm_name"] = self.df["standard_name"].apply(normalize_text)
        rows = []
        for _, r in self.df.iterrows():
            variants = {r["norm_name"]}
            variants |= {normalize_text(a) for a in r["aliases"].split("|") if a.strip()}
            for v in variants:
                if v:
                    rows.append({"dept_id": r["dept_id"], "level": r["level"],
                                 "standard_name": r["standard_name"], "variant": v})
        self.expanded = pd.DataFrame(rows)
        if self.expanded.empty:
            raise CodeBookError("codebook 展开后为空，请检查 standard_name/aliases 是否填写")
        self.vectorizer = TfidfVectorizer(analyzer="char", ngram_range=(1, 2))
        self.tfidf_matrix = self.vectorizer.fit_transform(self.expanded["variant"].tolist())

    # ---------- 修改操作 ----------
    def add_alias(self, dept_id: str, level: str, raw_name_norm: str) -> bool:
        mask = (self.df["dept_id"] == dept_id) & (self.df["level"] == level)
        if not mask.any():
            logger.error(f"add_alias 失败: 找不到 dept_id={dept_id}, level={level}")
            return False
        idx = self.df[mask].index[0]
        alias_set = {a for a in self.df.at[idx, "aliases"].split("|") if a.strip()}
        norm_name = self.df.at[idx, "norm_name"]
        if raw_name_norm in alias_set or raw_name_norm == norm_name:
            return False
        alias_set.add(raw_name_norm)
        self.df.at[idx, "aliases"] = "|".join(sorted(alias_set))
        self._build_index()
        logger.info(f"新增别名: dept_id={dept_id}, level={level}, alias='{raw_name_norm}'")
        return True

    def add_department(self, dept_id: str, level: str, standard_name: str, aliases: str = ""):
        if ((self.df["dept_id"] == dept_id) & (self.df["level"] == level)).any():
            raise CodeBookError(f"dept_id={dept_id}, level={level} 已存在，不能重复添加")
        new_row = pd.DataFrame([{"dept_id": dept_id, "level": level,
                                  "standard_name": standard_name, "aliases": aliases}])
        self.df = pd.concat([self.df, new_row], ignore_index=True)
        self._build_index()
        logger.info(f"新增部门: dept_id={dept_id}, level={level}, standard_name={standard_name}")

    def save(self):
        if os.path.exists(self.path):
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            backup_path = os.path.join(self.backup_dir, f"codebook_backup_{ts}.xlsx")
            try:
                shutil.copy2(self.path, backup_path)
                self._prune_backups()
            except Exception as e:
                logger.warning(f"备份 codebook 失败: {e}")
        tmp_path = self.path + ".tmp"
        self.df[self.REQUIRED_COLS].to_excel(tmp_path, index=False)
        os.replace(tmp_path, self.path)
        logger.info("codebook 已保存")

    def _prune_backups(self, keep: int = 20):
        files = sorted(
            (os.path.join(self.backup_dir, f) for f in os.listdir(self.backup_dir)),
            key=os.path.getmtime, reverse=True,
        )
        for f in files[keep:]:
            try:
                os.remove(f)
            except OSError:
                pass

    # ---------- 查询/浏览 ----------
    def search(self, level: Optional[str] = None, keyword: str = "") -> pd.DataFrame:
        df = self.df
        if level and level != "全部":
            df = df[df["level"] == level]
        if keyword:
            kw = normalize_text(keyword)
            df = df[df["norm_name"].str.contains(kw, na=False) |
                    df["aliases"].apply(lambda a: kw in normalize_text(a))]
        return df[self.REQUIRED_COLS]

    @property
    def stats(self) -> Dict[str, int]:
        return {
            "部门概念数": self.df["dept_id"].nunique(),
            "记录总行数": len(self.df),
            "变体总数(含别名)": len(self.expanded),
        }


# ============================================================
# DeptMatcher 匹配引擎
# ============================================================
class DeptMatcher:
    def __init__(self, codebook_path: str, model_path: Optional[str] = None):
        self.codebook = CodeBook(codebook_path)
        self.model_path = model_path
        self.model_bundle: Optional[dict] = None
        self._cache: Dict[Tuple[str, str], List[MatchResult]] = {}
        if model_path and os.path.exists(model_path):
            self._load_model(model_path)

    # ---------------- 模型管理 ----------------
    def _load_model(self, path: str):
        try:
            bundle = joblib.load(path)
            if bundle.get("feature_names") != FEATURE_NAMES:
                logger.warning("模型特征版本与当前程序不一致，回退到启发式模式")
                self.model_bundle = None
                return
            self.model_bundle = bundle
            logger.info(f"模型加载成功: {path}, 训练时间={bundle.get('trained_at')}")
        except Exception as e:
            logger.error(f"模型加载失败: {e}，回退到启发式模式")
            self.model_bundle = None

    @property
    def model_status(self) -> str:
        if self.model_bundle is None:
            return "启发式模式（尚未训练模型）"
        m = self.model_bundle
        metrics = m.get("metrics", {})
        top3 = metrics.get("top3_acc")
        top3_str = f"{top3:.1%}" if top3 is not None else "N/A"
        return f"已训练模型（{m.get('model_type')}，Top3准确率={top3_str}，训练于{m.get('trained_at')}）"

    def _predict(self, feat_vec: np.ndarray) -> float:
        if self.model_bundle is not None:
            try:
                proba = self.model_bundle["model"].predict_proba(feat_vec.reshape(1, -1))[0, 1]
                return float(proba)
            except Exception as e:
                logger.error(f"模型预测出错，回退启发式算法: {e}")
        return heuristic_score(feat_vec)

    # ---------------- 单条查询：全量精确比对 ----------------
    def _score_all_variants(self, raw_n: str, level: str) -> pd.DataFrame:
        exp = self.codebook.expanded
        mask = (exp["level"] == level).values
        if not mask.any():
            raise MatcherError(f"codebook 中没有 level='{level}' 的任何记录")
        sub = exp[mask].reset_index(drop=True)
        raw_vec = self.codebook.vectorizer.transform([raw_n])
        sims = cosine_similarity(raw_vec, self.codebook.tfidf_matrix[mask])[0]

        n = len(sub)
        feat_matrix = np.zeros((n, len(FEATURE_NAMES)))
        for i in range(n):
            feat_matrix[i] = extract_features(raw_n, sub.at[i, "variant"], sims[i])
        scores = np.array([self._predict(feat_matrix[i]) for i in range(n)])

        sub = sub.copy()
        sub["score"] = scores
        best = sub.sort_values("score", ascending=False).drop_duplicates("dept_id", keep="first")
        return best[["dept_id", "standard_name", "score"]].reset_index(drop=True)

    def query(self, raw_name: str, dtype_t: str, topk: int = 3, use_cache: bool = True) -> pd.DataFrame:
        level = map_level(dtype_t)
        raw_n = normalize_text(raw_name)
        if not raw_n:
            raise MatcherError("原始部门名称为空，无法匹配")

        cache_key = (raw_n, level)
        if use_cache and cache_key in self._cache:
            results = self._cache[cache_key]
        else:
            best = self._score_all_variants(raw_n, level).sort_values("score", ascending=False)
            results = [
                MatchResult(r.dept_id, r.standard_name, round(float(r.score), 4),
                            confidence_tier(r.score))
                for r in best.head(10).itertuples()
            ]
            self._cache[cache_key] = results

        out = pd.DataFrame([r.__dict__ for r in results[:topk]])
        if not out.empty:
            out.insert(0, "rank", range(1, len(out) + 1))
        return out

    # ---------------- 批量查询：两阶段"检索+精排" ----------------
    def _stage1_candidates(self, raw_list: List[str], level: str, topn: int
                            ) -> Dict[str, List[Tuple[str, str, float]]]:
        """TF-IDF向量化快速粗筛，返回 {raw_norm: [(dept_id, variant, tfidf_cos), ...]}"""
        exp = self.codebook.expanded
        mask = (exp["level"] == level).values
        if not mask.any():
            return {r: [] for r in raw_list}
        sub = exp[mask].reset_index(drop=True)
        sub_matrix = self.codebook.tfidf_matrix[mask]

        result: Dict[str, List[Tuple[str, str, float]]] = {}
        chunk = CFG.chunk_size
        for start in range(0, len(raw_list), chunk):
            block = raw_list[start:start + chunk]
            raw_matrix = self.codebook.vectorizer.transform(block)
            sims = cosine_similarity(raw_matrix, sub_matrix)
            for i, raw_n in enumerate(block):
                row = sims[i]
                order = np.argsort(-row)
                seen, picked = set(), []
                for j in order:
                    dept_id = sub.at[int(j), "dept_id"]
                    if dept_id in seen:
                        continue
                    seen.add(dept_id)
                    picked.append((dept_id, sub.at[int(j), "variant"], float(row[j])))
                    if len(picked) >= topn:
                        break
                result[raw_n] = picked
        return result

    def _dept_standard_name(self, dept_id: str, fallback: str) -> str:
        row = self.codebook.expanded[self.codebook.expanded["dept_id"] == dept_id]
        return row.iloc[0]["standard_name"] if len(row) else fallback

    def _rerank(self, raw_n: str, candidates: List[Tuple[str, str, float]]) -> List[MatchResult]:
        if not candidates:
            return []
        rows = []
        for dept_id, variant, tfidf_cos in candidates:
            feat = extract_features(raw_n, variant, tfidf_cos)
            score = self._predict(feat)
            rows.append((dept_id, self._dept_standard_name(dept_id, variant), score))
        rows.sort(key=lambda x: -x[2])
        return [MatchResult(d, s, round(float(sc), 4), confidence_tier(sc)) for d, s, sc in rows]

    def batch_query(self, df: pd.DataFrame, topk: int = 3,
                     col_name: str = "w_name_o", col_level: str = "dtype_t",
                     progress_callback=None) -> pd.DataFrame:
        if col_name not in df.columns or col_level not in df.columns:
            raise MatcherError(f"输入数据必须包含列: {col_name}, {col_level}")

        work = df.copy()
        work["_raw_n"] = work[col_name].apply(normalize_text)
        work["_level"] = None
        for idx, v in work[col_level].items():
            try:
                work.at[idx, "_level"] = map_level(v)
            except MatcherError:
                pass

        total, done = len(work), 0
        result_map: Dict[Tuple[str, str], List[MatchResult]] = {}

        for level, group in work.groupby("_level", dropna=True):
            unique_raw = [r for r in group["_raw_n"].unique() if r]
            to_compute = [r for r in unique_raw if (r, level) not in self._cache]
            if to_compute:
                cand_map = self._stage1_candidates(to_compute, level, CFG.stage1_topn)
                for raw_n in to_compute:
                    self._cache[(raw_n, level)] = self._rerank(raw_n, cand_map.get(raw_n, []))
            for raw_n in unique_raw:
                result_map[(raw_n, level)] = self._cache.get((raw_n, level), [])
            done += len(group)
            if progress_callback:
                progress_callback(done, total)

        records = []
        for _, r in work.iterrows():
            raw_n, level = r["_raw_n"], r["_level"]
            rec = {col_name: r[col_name], col_level: r[col_level]}
            if not raw_n:
                rec["_备注"] = "原始名称为空"
                results = []
            elif level is None:
                rec["_备注"] = "无法识别的 dtype_t"
                results = []
            else:
                results = result_map.get((raw_n, level), [])
                rec["_备注"] = "" if results else "未找到候选，建议人工核查/新增部门"
            for i in range(topk):
                if i < len(results):
                    rec[f"候选{i+1}"] = results[i].standard_name
                    rec[f"dept_id{i+1}"] = results[i].dept_id
                    rec[f"得分{i+1}"] = results[i].score
                    rec[f"置信度{i+1}"] = results[i].confidence
                else:
                    rec[f"候选{i+1}"], rec[f"dept_id{i+1}"] = "", ""
                    rec[f"得分{i+1}"], rec[f"置信度{i+1}"] = np.nan, ""
            records.append(rec)
        return pd.DataFrame(records)

    # ---------------- 人工反馈：确认 / 标记无匹配 ----------------
    def confirm(self, raw_name: str, dtype_t: str, dept_id: str,
                log_path: str = "confirmed_log.xlsx"):
        level = map_level(dtype_t)
        raw_n = normalize_text(raw_name)
        if self.codebook.add_alias(dept_id, level, raw_n):
            self.codebook.save()
        self._cache.pop((raw_n, level), None)
        log_row = pd.DataFrame([{"w_name_o": raw_name, "dtype_t": dtype_t,
                                  "dept_id": dept_id, "confirmed_at": datetime.now().isoformat()}])
        self._append_log(log_row, log_path)
        logger.info(f"用户确认: '{raw_name}'({dtype_t}) -> {dept_id}")

    def flag_unmatched(self, raw_name: str, dtype_t: str, note: str = "",
                        log_path: str = "unmatched_log.xlsx"):
        log_row = pd.DataFrame([{"w_name_o": raw_name, "dtype_t": dtype_t,
                                  "note": note, "flagged_at": datetime.now().isoformat()}])
        self._append_log(log_row, log_path)
        logger.info(f"标记为无匹配: '{raw_name}'({dtype_t})")

    @staticmethod
    def _append_log(new_rows: pd.DataFrame, log_path: str):
        if os.path.exists(log_path):
            combined = pd.concat([pd.read_excel(log_path), new_rows], ignore_index=True)
        else:
            combined = new_rows
        tmp = log_path + ".tmp"
        combined.to_excel(tmp, index=False)
        os.replace(tmp, log_path)

    # ---------------- 模型训练与评估 ----------------
    def _raw_features_for_training(self, raw_n: str, level: str) -> Dict[str, Tuple[np.ndarray, float]]:
        exp = self.codebook.expanded
        mask = (exp["level"] == level).values
        if not mask.any():
            raise MatcherError(f"level={level} 不存在于 codebook")
        sub = exp[mask].reset_index(drop=True)
        raw_vec = self.codebook.vectorizer.transform([raw_n])
        sims = cosine_similarity(raw_vec, self.codebook.tfidf_matrix[mask])[0]

        best: Dict[str, Tuple[np.ndarray, float]] = {}
        for i in range(len(sub)):
            feat = extract_features(raw_n, sub.at[i, "variant"], sims[i])
            h = heuristic_score(feat)
            dept_id = sub.at[i, "dept_id"]
            if dept_id not in best or h > best[dept_id][1]:
                best[dept_id] = (feat, h)
        return best

    def train(self, training_data_path: str, model_out: str,
              model_type: str = "logistic", test_size: float = 0.2,
              hard_negatives: int = 6, random_state: int = 42) -> dict:
        df = pd.read_excel(training_data_path, dtype=str).fillna("")
        required = {"w_name_o", "dtype_t", "dept_id"}
        if not required.issubset(df.columns):
            raise MatcherError(f"训练数据缺少必要列: {required - set(df.columns)}")

        valid_rows = []
        for _, r in df.iterrows():
            try:
                level = map_level(r["dtype_t"])
            except MatcherError:
                continue
            raw_n = normalize_text(r["w_name_o"])
            if raw_n and r["dept_id"]:
                valid_rows.append((raw_n, level, r["dept_id"]))

        n_total = len(valid_rows)
        if n_total < 10:
            raise MatcherError(f"有效训练样本过少({n_total}条)，无法训练")

        do_split = n_total >= 30
        if do_split:
            train_rows, val_rows = train_test_split(valid_rows, test_size=test_size,
                                                       random_state=random_state)
        else:
            train_rows, val_rows = valid_rows, []
            logger.warning("训练样本量过小，跳过验证集评估")

        def build_xy(rows):
            X, y = [], []
            for raw_n, level, true_id in rows:
                try:
                    scored = self._raw_features_for_training(raw_n, level)
                except MatcherError:
                    continue
                if true_id not in scored:
                    continue
                pos_feat, _ = scored[true_id]
                X.append(pos_feat); y.append(1)
                negs = sorted(((d, f, h) for d, (f, h) in scored.items() if d != true_id),
                              key=lambda t: -t[2])[:hard_negatives]
                for _, f, _ in negs:
                    X.append(f); y.append(0)
            return np.array(X), np.array(y)

        def make_model():
            if model_type == "logistic":
                return LogisticRegression(class_weight="balanced", max_iter=1000)
            return RandomForestClassifier(n_estimators=300, class_weight="balanced",
                                           max_depth=8, random_state=random_state)

        X_train, y_train = build_xy(train_rows)
        if len(y_train) == 0 or len(set(y_train.tolist())) < 2:
            raise MatcherError("训练特征生成失败或类别单一，请检查训练数据与codebook是否对应")
        model = make_model()
        model.fit(X_train, y_train)

        metrics = {"n_train": len(train_rows), "n_val": len(val_rows)}
        if val_rows:
            self.model_bundle = {"model": model, "feature_names": FEATURE_NAMES}
            self._cache.clear()
            top1 = top3 = 0
            for raw_n, level, true_id in val_rows:
                try:
                    best = self._score_all_variants(raw_n, level).sort_values("score", ascending=False)
                except MatcherError:
                    continue
                top_ids = best["dept_id"].tolist()
                top1 += int(top_ids[:1] == [true_id])
                top3 += int(true_id in top_ids[:3])
            metrics["top1_acc"] = top1 / len(val_rows)
            metrics["top3_acc"] = top3 / len(val_rows)

        # 用全部数据重新训练最终部署模型
        X_all, y_all = build_xy(valid_rows)
        final_model = make_model()
        final_model.fit(X_all, y_all)

        bundle = {
            "model": final_model,
            "feature_names": FEATURE_NAMES,
            "model_type": model_type,
            "metrics": metrics,
            "trained_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        }
        joblib.dump(bundle, model_out)
        self.model_bundle = bundle
        self._cache.clear()
        logger.info(f"模型训练完成: {metrics}")
        return metrics